name: Cypress Tests

on:
  push:
    branches:
      - main
      - lesson-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Start http-server
        run: npm run serve &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests
        run: npm run myCypress -- --spec "cypress/e2e/test2.cy.js,cypress/e2e/responsive.cy.js"

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
